version: '3.9'
services:
  web:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - ${APP_PORT}:8080
    networks:
      - default
    volumes:
      - data:/app/data
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  default:
    name: docker_dozzle_network
    driver: bridge

volumes:
  data:
    name: docker_dozzle_data
    driver: local
