version: '3.9'
services:
  web:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - ${APP_PORT}:8080
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  default:
    driver: bridge
